### ISSUE TITLE
Can't get the extension to work in vscode extension debugger

### ISSUE THREAD

**Issue by viciious** [Hazelight/vscode-unreal-angelscript#9]
Hi!

Running the extension in dev mode produces the following error:

```
Debugger listening on ws://127.0.0.1:6009/e15db50e-1d33-4325-b3de-649ff74998bc
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/Victor/Documents/vscode-unreal-angelscript/extension/server/server.js'
Require stack:
- /Users/Victor/Documents/vscode-unreal-angelscript/extension/node_modules/vscode-languageclient/lib/utils/electronForkStart.js
    at Function._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at internal/modules/cjs/loader.js:622:27
    at electron/js2c/asar.js:717:26
    at Function._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Server.<anonymous> (/Users/Victor/Documents/vscode-unreal-angelscript/extension/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at Server.emit (events.js:203:13)
    at Pipe.onconnection (net.js:1473:8) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Victor/Documents/vscode-unreal-angelscript/extension/node_modules/vscode-languageclient/lib/utils/electronForkStart.js'
  ]
}
[Info  - 12:20:26 AM] Connection to server got closed. Server will restart.
```

Tried all kinds of different things to no avail, including running 'npm install' in extension directories. Any tips on getting this to work?

**Comment by GGLucas** [comment]
I usually run the `compile:server` or `watch:server` scripts defined in the top-level package.json

I don't know very much about npm packaging though, most of the packaging for this extension is copied from an older version of the language server example extension in the vscode docs.

**Comment by viciious** [comment]
> I usually run the `compile:server` or `watch:server` scripts defined in the top-level package.json

Yup, that worked! Kinda counterintuitive but good enough for me, thanks!
